#include <Date.au3>
#include <FileConstants.au3>
#include <WinAPIFiles.au3>

Func Daily($CSV, $Macro, $FileName)
    Run("C:\Program Files (x86)\Microsoft Office\Office15\Excel.exe" & " " & $CSV, "E:\Reports\New")
    Sleep(8000)
    Send("!l")
    Sleep(1000)
    Send("pm")
    Sleep(1000)
    Send($Macro, 1)
    Send("{TAB 3}")
    Sleep(1000)
    Send("{ENTER}")
    Sleep(500)
    WinWaitActive($CSV & " - Excel")
    Sleep(8000)
    Send("{HOME}")
    Sleep(1000)
    Send("!f")
    Sleep(1000)
    Send("a")
    Sleep(500)
    Send("1")
    Sleep(2000)
    Send("{TAB}")
    Sleep(1000)
    Send("{DOWN}")
    Sleep(1000)
    Send("{UP 10}")
    Sleep(500)
    Send("{UP 10}")
    Sleep(500)
	Send("{UP 10}")
    Sleep(500)
    Send("{ENTER}")
    Sleep(1000)
    Send("{SHIFTDOWN}")
    Send("{TAB}")
    Send("{SHIFTUP}")
    Sleep(500)
    Send("{DEL}")
    Sleep(500)
    Send("{HOME}")
    Sleep(500)
    Local $Today=_DateToDayValue(@YEAR,@MON,@MDAY),$Y, $M, $D
    $Today=_DayValueToDate($Today, $Y, $M, $D)
    $Y = StringTrimLeft($Y, 2)
    $Today=StringFormat("%02i.%02i.%02i", $M,  $D,  $Y)
    Send($FileName & " " & $Today)
    Sleep(500)
    Send("{ENTER}")
    Sleep(500)
    Send("!{F4}")
    Sleep(500)
    Send("!{F4}")
    Sleep(500)
EndFunc

Func Report($CSV, $Macro, $FileName)
    Run("C:\Program Files (x86)\Microsoft Office\Office15\Excel.exe" & " " & $CSV, "E:\Reports\New")
    Sleep(5000)
    Send("!l")
    Sleep(1000)
    Send("pm")
    Sleep(1000)
    Send($Macro, 1)
    Send("{TAB 3}")
    Sleep(1000)
    Send("{ENTER}")
    Sleep(500)
    WinWaitActive($CSV & " - Excel")
    Sleep(8000)
    Send("{HOME}")
    Sleep(500)
    Send("!f")
    Sleep(500)
    Send("a")
    Sleep(500)
    Send("1")
    Sleep(2000)
    Send("{TAB}")
    Sleep(1000)
    Send("{DOWN}")
    Sleep(1000)
    Send("{UP 10}")
    Sleep(500)
    Send("{UP 10}")
    Sleep(500)
	Send("{UP 10}")
    Sleep(500)
    Send("{ENTER}")
    Sleep(1000)
    Send("{SHIFTDOWN}")
    Send("{TAB}")
    Send("{SHIFTUP}")
    Sleep(500)
    Send("{DEL}")
    Sleep(500)
    Send("{HOME}")
    Sleep(500)
    Send($FileName)
    Sleep(500)
    Send("{ENTER}")
    Sleep(500)
    Send("!{F4}")
    Sleep(500)
    Send("!{F4}")
    Sleep(500)
EndFunc

$FileExists = 0
$FileExists = FileExists("E:\Reports\New\CR026.csv")
If $FileExists Then Report('CR026.csv', 'Macros.xlsm!CR026M', 'CR026 Computers Not Actively Reporting')
$FileExists = 0
$FileExists = FileExists("E:\Reports\New\CR063.csv")
If $FileExists Then Report('CR063.csv', 'Macros.xlsm!CR063M', 'CR063 Patch Levels')
$FileExists = 0
$FileExists = FileExists("E:\Reports\New\CR064.csv")
If $FileExists Then Report('CR064.csv', 'Macros.xlsm!CR064M', 'R064 Computers Missing Patches')
$FileExists = 0
$FileExists = FileExists("E:\Reports\New\CR066.csv")
If $FileExists Then Report('CR066.csv', 'Macros.xlsm!CR066M', 'CR066 Admin User Accounts')
$FileExists = 0
$FileExists = FileExists("E:\Reports\New\CR067.csv")
If $FileExists Then Report('CR067.csv', 'Macros.xlsm!CR067M', 'CR067 Computer Utilization (CR026)')
$FileExists = 0
$FileExists = FileExists("E:\Reports\New\CR068.csv")
If $FileExists Then Report('CR068.csv', 'Macros.xlsm!CR068M', 'CR068 Disk Space Usage')
$FileExists = 0
$FileExists = FileExists("E:\Reports\New\Daily.csv")
If $FileExists Then Daily('Daily.csv', 'Macros.xlsm!Daily', 'OS Report')
$FileExists = 0
$FileExists = FileExists("E:\Reports\New\Hardware.csv")
If $FileExists Then Report('Hardware.csv', 'Macros.xlsm!HWReport', 'Hardware Report Full List of Hardware')
